### ISSUE TITLE
Add unit tests for storage

### ISSUE THREAD

**Issue by kuroidoruido** [kuroidoruido/ShieldDB#2]
The project is working but have a very big issue: there is no tests. Everything is tested by hand...

The goal here is to add unit tests to every storages

**Comment by HristianIliev** [comment]
I can take this up, but can you tell me which classes exactly do you refer as Storage

**Comment by kuroidoruido** [comment]
@dearrudam already made a PR for the issue, but you can have a look on his PR if you want to add more tests :slightly_smiling_face:
