### ISSUE TITLE
Add unit tests for mappers

### ISSUE THREAD

**Issue by kuroidoruido** [kuroidoruido/ShieldDB#3]
The project is working but have a very big issue: there is no tests. Everything is tested by hand...

The goal here is to add unit tests to every mappers

**Comment by HristianIliev** [comment]
I can take this up, but please tell me which classes do you refer as Mappers

**Comment by kuroidoruido** [comment]
When I refer to Mappers I think about ShieldDBGson class (in the shielddb-gson-backend project) and the usage of the instance of ShieldDbJsonMapper in the BottomShield class

**Comment by HristianIliev** [comment]
Sure, then you can assign me.

**Comment by kuroidoruido** [comment]
@monil @HristianIliev  @bhegmanns both of you are making tests for this issue, but I will not keep both 3 PRs. Can merge your 3 PRs is one?
